version: '3.8'
services:
  rpi4:
    image: includekhs/final:6.0
    container_name: rpi4
    working_dir: /app/raspberrypi4
    command: python3 rpi_mqtt.py
    tty: true
    privileged: true

  opi0:
    image: includekhs/final:6.0
    container_name: opi0
    working_dir: /app/orangepi0/DHT11-DHT22-Python-library-Orange-PI
    command: python3 opi_mqtt.py
    tty: true
    privileged: true

  opi03:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opi03
    working_dir: /app/orangepi03
    command: bash
    tty: true
    volumes:
      - app-data:/app/orangepi03/data 

volumes:
  app-data:


